-- return {
-- 	"nvimtools/none-ls.nvim",
-- 	dependencies = {
-- 		"jay-babu/mason-null-ls.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 	},
-- 	config = function()
-- 		local null_ls = require("null-ls")
-- 		local formatting = null_ls.builtins.formatting
-- 		local sources = {
-- 			formatting.stylua,
-- 			formatting.prettier,
-- 			formatting.autopep8,
-- 			formatting.black,
-- 			formatting.isort,
-- 			formatting.eslint_d,
-- 		}
-- 		null_ls.setup({
-- 			sources = sources,
-- 		})
		
-- 		-- Setup mason-null-ls
-- 		require("mason-null-ls").setup({
-- 			ensure_installed = {
-- 				"stylua",
-- 				"prettier",
-- 				"autopep8",
-- 				"black",
-- 				"isort",
-- 				"eslint_d",
-- 			},
-- 			automatic_installation = true,
-- 		})
-- 	end,
-- }
